version: "3.9"
services:
  postgres:
    image: kartoza/postgis:13.0
    ports:
      - "5432:5432"
    networks:
      - testnetwork
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DBNAME=my-postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASS=mypassword

networks:
  testnetwork:
volumes:
  postgres:
    driver: local
